{
  "timestamp": "2025-02-06T09:02:29.586386",
  "total_duration": 6.6080190000000005,
  "failed_categories": [
    "core",
    "models",
    "api",
    "integration"
  ],
  "category_reports": [
    {
      "category": "core",
      "timestamp": "2025-02-06T09:02:24.879569",
      "duration": 1.901836,
      "results": {
        "passed": 0,
        "failed": 0,
        "skipped": 0,
        "errors": 0,
        "total": 0
      },
      "coverage": "No coverage data",
      "returncode": 4,
      "output": "ImportError while loading conftest '/Users/jameshightower/Desktop/AppAcademy/capstone/projects/Harmonic-Universe/backend/tests/conftest.py'.\ntests/conftest.py:22: in <module>\n    from app.main import app\napp/main.py:13: in <module>\n    from app.db.session import SessionLocal\nE   ModuleNotFoundError: No module named 'app.db'\n"
    },
    {
      "category": "models",
      "timestamp": "2025-02-06T09:02:26.452152",
      "duration": 1.572305,
      "results": {
        "passed": 0,
        "failed": 0,
        "skipped": 0,
        "errors": 0,
        "total": 0
      },
      "coverage": "No coverage data",
      "returncode": 4,
      "output": "ImportError while loading conftest '/Users/jameshightower/Desktop/AppAcademy/capstone/projects/Harmonic-Universe/backend/tests/conftest.py'.\ntests/conftest.py:22: in <module>\n    from app.main import app\napp/main.py:13: in <module>\n    from app.db.session import SessionLocal\nE   ModuleNotFoundError: No module named 'app.db'\n"
    },
    {
      "category": "api",
      "timestamp": "2025-02-06T09:02:28.028592",
      "duration": 1.576274,
      "results": {
        "passed": 0,
        "failed": 0,
        "skipped": 0,
        "errors": 0,
        "total": 0
      },
      "coverage": "No coverage data",
      "returncode": 4,
      "output": "ImportError while loading conftest '/Users/jameshightower/Desktop/AppAcademy/capstone/projects/Harmonic-Universe/backend/tests/conftest.py'.\ntests/conftest.py:22: in <module>\n    from app.main import app\napp/main.py:13: in <module>\n    from app.db.session import SessionLocal\nE   ModuleNotFoundError: No module named 'app.db'\n"
    },
    {
      "category": "integration",
      "timestamp": "2025-02-06T09:02:29.586370",
      "duration": 1.557604,
      "results": {
        "passed": 0,
        "failed": 0,
        "skipped": 0,
        "errors": 0,
        "total": 0
      },
      "coverage": "No coverage data",
      "returncode": 4,
      "output": "ImportError while loading conftest '/Users/jameshightower/Desktop/AppAcademy/capstone/projects/Harmonic-Universe/backend/tests/conftest.py'.\ntests/conftest.py:22: in <module>\n    from app.main import app\napp/main.py:13: in <module>\n    from app.db.session import SessionLocal\nE   ModuleNotFoundError: No module named 'app.db'\n"
    }
  ]
}